name: test for ec github action
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run EC Validator (long-lived)
      uses: enterprise-contract/action-validate-image@v1.1
      with:
        image: "quay.io/redhat-appstudio/ec-golden-image:latest"
        key: ${{ vars.PUBLICKEY }}
        policy: "github.com/enterprise-contract/config//default"
        extra-params: --ignore-rekor

    - name: Run EC Validator (keyless)
      uses: enterprise-contract/action-validate-image@v1.1
      with:
        image: quay.io/lucarval/festoji:latest
        identity: https:\/\/github\.com\/(slsa-framework\/slsa-github-generator|lcarva\/festoji)\/
        issuer: https://token.actions.githubusercontent.com
