name: example of action validate image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run EC Validator
      uses: seanconroy2021/action-validate-image@main
      with:
        option: long-lived
        image: quay.io/redhat-appstudio/ec-golden-image:latest
        key: ${{ vars.PUBLICKEY }}
        policy: github.com/enterprise-contract/config//slsa3

